### ISSUE TITLE
"Show in Menu Bar" Reactiavtion

### ISSUE THREAD

**Issue by iBastel** [amebalabs/TRex#10]
I actually don't find a way to reactivate the icon back to menu bar to change some settings. TRex is running but not accessible.

**Comment by melonamin** [comment]
If you launch TRex again, when it's running and not showing the menu bar item, it should open the preferences screen.

If that doesn't work use url-scheme to open preferences `trex://showPreferences`

**Comment by iBastel** [comment]
Thanks! Works perfect. Didn't found it in the documentation.
