### ISSUE TITLE
Shortcut Modifiers General Usage

### ISSUE THREAD

**Issue by moshed** [amebalabs/TRex#14]
A few issues:

- I cant seem to set a shortcut to a number with control-option-command as modifier. It just sets it to cmd-v for some reason
- I try set cmd-shift-option-O and it says it taken by stem but I checked and nothings using it. 
- cmd-shift-option-M refuses to set. Just stays at whatever it was set previously.

**Comment by melonamin** [comment]
I'm 99% sure the problem is not in TRex, I've tested it on a couple of different machines...
Can you may be create a new test account on your Mac and see if it works there?

**Comment by moshed** [comment]
ok will do and report back! 
if it works for you on a few machines and not for me your likely right. of note I do have bettertouchtool installed which in my mind is the most likely culprit so I will try disabling that first
