### ISSUE TITLE
Notifications on completion

### ISSUE THREAD

**Issue by moshed** [amebalabs/TRex#15]
would it be possible to add some kind of visual indicator to indicate completion? maybe  a full blown notification or add a checkmark to the menubar icon kinda thing

**Comment by melonamin** [comment]
Recognition is pretty much instantaneous, why you in need of such indicator?

**Comment by moshed** [comment]
I've seen another app that includes the text copied in the notification so that you can see that it correctly recognized the text you wanted so you don't have to go to the intended destination and paste it wrong. 

Now that I write it out seems pretty niche though!

**Comment by melonamin** [comment]
Ok, try it
[TRex.app.zip](https://github.com/amebalabs/TRex/files/7464552/TRex.app.zip)

**Comment by moshed** [comment]
amazing! works beautifully!
