### ISSUE TITLE
No Status Bar Icon

### ISSUE THREAD

**Issue by githubwoolf** [amebalabs/TRex#16]
TRex runs, but I don't see any status bar icon.

![image](https://user-images.githubusercontent.com/4638824/150114693-513629bb-6c71-4691-9b54-8eaed3c13242.png)

**Comment by melonamin** [comment]
TRex has an option to hide menu bar icon in Preferences, could you have toggled it?

Open this URL `trex://showPreferences`, this will present TRex Preferences.

**Comment by githubwoolf** [comment]
Oh, great thx!
