### ISSUE TITLE
Can't get to preferences

### ISSUE THREAD

**Issue by acmay** [amebalabs/TRex#18]
When I first opened the App I uncheck many of the preferences and now I can't seem to get them back.

I tried the "trex://showPreferences" in Safari and I click Allow to open the app but nothing appears.
Checking with "Mission Control" doesn't show any windows that are hiding.
I tried deleting com.ameba.Trex files in ~/Library along with an uninstall and reinstall.

The CLI command does seem to trigger the app/mouse icon but I don't see anything show up in the clipboard.

I have version 1.5.0 from homebrew.

**Comment by melonamin** [comment]
Hey,

>I uncheck many of the preferences and now I can't seem to get them back.
You can't use the menu bar item as well, correct?

>I tried deleting com.ameba.Trex files in ~/Library

If you want to reset TRex, you need to delete files from Group Containers:

```bash
➜  ~ cd ~/Library/Group\ Containers
➜  Group Containers ls | grep X93LWC49WV.TRex
X93LWC49WV.TRex
X93LWC49WV.TRex.preferences
```

>I tried the "trex://showPreferences" in Safari and I click Allow to open the app but nothing appears.

`trex://showPreferences` indeed seesm to be broken in this release, I'll take a look.
