### ISSUE TITLE
Preferences menu option gone

### ISSUE THREAD

**Issue by jacopo-j** [amebalabs/TRex#28]
Hi, after upgrading to version 1.6.0 it looks like the "Preferences" menu option has disappeared.

<img width="253" alt="Screenshot 2022-12-24 alle 13 11 13" src="https://user-images.githubusercontent.com/9914547/209435868-1a7e1ff5-e775-4ad0-adec-16bf008f4630.png">

Also, I cannot reach the preferences window using `trex://showPreferences` anymore.

**Comment by melonamin** [comment]
What version of macOS are you on?

**Comment by jacopo-j** [comment]
13.1 (22C65)

**Comment by melonamin** [comment]
Hmmm... I'm on the same version and Settings are there. Let me think about what can cause that

![Screenshot 2022-12-24 at 17 55 33](https://user-images.githubusercontent.com/222100/209452787-aae91901-aa4f-486e-ba4d-1451d8997097.png)

**Comment by nKolja** [comment]
I just want to add that I have the same problem, ```trex://showPreferences``` doesn't work, and furthermore, I cannot open the open the app at all. I turned off the menu item by preference, so the app is inaccessible through the menu bar. I expected to open it by opening the app file, but that doesn't work. The app runs in the background, it works, I can kill it and re-open it, and it will continue working, but there is no way (to the best of my knowledge) to open the settings pane.

**Comment by melonamin** [comment]
Hi @nKolja,

you can try running this in Terminal to put TRex menubar icon back - `defaults write com.ameba.TRex ShowMenuBarIcon 1`

**Comment by Din0Git** [comment]
Hi There,

Did somebody find a solution for the missing TRex missing menu bar? Can not for the life in me find the settings.

**Comment by melonamin** [comment]
@Din0Git what macOs version are you on?

As a workaround you can try downgrading to 1.5.2, tweak the settings and go back to 1.6

**Comment by Flippchen** [comment]
Hey,

have the same issue. Downgrading did not help. `trex://showPreferences` does not open the settings nevertheless which version I use. Capture command still functions.

**Comment by melonamin** [comment]
@Flippchen which version of macOS are you on? Have you tried deleting all preferences?

**Comment by Flippchen** [comment]
@melonamin I currently have macOS Sonoma(14.2). How can I delete all preferences?

**Comment by melonamin** [comment]
The easiest way would be to uninstall TRex with [AppCleaner](https://freemacsoft.net/appcleaner/). Then reinstall the app

**Comment by Flippchen** [comment]
@melonamin Thanks, that worked. I have reinstalled the tool and the functionality is back, thanks. But I still can not edit the Preferences. The command in the Browser does also not help either.
![image](https://github.com/amebalabs/TRex/assets/91947480/a17d681d-7a2a-4c14-9941-b8d1c6b12252)

**Comment by melonamin** [comment]
Ok, let me give this another look, this is super weird.

What is your macOS system language is set to?

**Comment by Flippchen** [comment]
![image](https://github.com/amebalabs/TRex/assets/91947480/7bdd8775-bc6f-4b11-ad4c-05944229454d)

**Comment by melonamin** [comment]
@Flippchen Can you try this build please?
[TRex.app.zip](https://github.com/amebalabs/TRex/files/14084517/TRex.app.zip)

**Comment by Flippchen** [comment]
Hey @melonamin, that solved one of the two problems. When I have the icon in the status bar, I can now go to the settings. But if I turn off the icon, I cannot access the settings via the browser command.  I am curious, what solved the first problem?

**Comment by melonamin** [comment]
@Flippchen check out this build, should adress the remaining issue.  [TRex.app.zip](https://github.com/amebalabs/TRex/files/14105190/TRex.app.zip)


> I am curious, what solved the first problem?

In short macOS changed the way you can open Preferences\Settings programmatically, there 3 ways to do it now: one for macOS 14, one for macOS 13 and another one for all previous versions...

I was using a dirty hack to get around it, now I switche to a less dirty hack 🙃

**Comment by Flippchen** [comment]
@melonamin Unfortunately, the preferences still do not show up with the provided command, If I hide the icon in the menu bar. 

Thanks for the explanation:)

**Comment by gcarlino** [comment]
Hello everybody and @melonamin, preferences did not show up with 1.6.0. The latest build 1.7.0 (109) solved the issues and I am able to re-activate the settings with the URL scheme `trex://captureclipboard`. The terminal command still does not work.
I am with macOS 14.3.

By the way, thanks for the amazing work.

**Comment by melonamin** [comment]
> Unfortunately, the preferences still do not show up with the provided command

@Flippchen can you see if there is any relevant output in Console.app when you trying to open the Preferences thorugh URL-scheme? It works 100% of the time for me, I can't reproduce the problem...


> The terminal command still does not work

@gcarlino Can you elaborate please?

**Comment by Flippchen** [comment]
@melonamin I got it to work, but I don't know exactly how. I simply removed the app and all saved data and installed the new version as before.

**Comment by melonamin** [comment]
I see. The app should register itself with the system during install, sometimes it is flaky...

Thanks, I'm going to release this version

**Comment by gcarlino** [comment]
> > The terminal command still does not work
> 
> @gcarlino Can you elaborate please?

I mean that I am not able to reactivate the menu bar with the `defaults write com.ameba.TRex ShowMenuBarIcon 1` command.
