### ISSUE TITLE
OCR a pdf with multiple pages

### ISSUE THREAD

**Issue by lologhi** [amebalabs/TRex#29]
Hi! Thanks a lot for this great tool!
The new feature "Drag&Drop an image on the menu bar item to OCR it" made me dream of a solution where I could drag and drop a PDF file with multiple pages for OCR.

**Comment by melonamin** [comment]
I've played around with this idea but couldn't find a good way to implement it. OCR for large documents can take some time and requires additional UI.

I've decided to not add this feature at this moment.

**Comment by lologhi** [comment]
You did well. I've found in between another app that does this job, Textify.
