### ISSUE TITLE
FR: Menu item to invoke OCR on clipboard content (without enabling full Capture access)

### ISSUE THREAD

**Issue by manastungare** [amebalabs/TRex#30]
For privacy reasons, it seems best if I copied content to the clipboard myself instead of granting access to this (or any other) app to perform screen recording.

Although I could set a global hotkey to quickly have the clipboard content OCRd, there appears to be no menu item to do exactly that.

If there’s a concern about too many menu items, perhaps the existing Capture menu item could first check if there’s an image on the clipboard, and if (and only if) not, proceed to record the screen.

Is this on the roadmap? If not, would you be willing to consider? Thank you for this awesome tool!

**Comment by melonamin** [comment]
I like the idea, should be easy to implement 👍

Another option that may work for you in the meanwhile, TRex has System Services menu integration:

![Screenshot 2024-01-03 at 15 39 27](https://github.com/amebalabs/TRex/assets/222100/4f6d8d9f-a0d4-4c8e-b9ca-06b6ac9e7829)

**Comment by manastungare** [comment]
Awesome, thanks for the quick response!

The Services menu would work well for files, but I am still thinking of screenshots where the content likely comes from a portion of a web page or a (web) doc that’s not a local file. Having to save it to a file first would be a pain.

**Comment by manastungare** [comment]
Thanks for the quick response, I appreciate it! Bought via the Mac App Store in appreciation!
