### ISSUE TITLE
Apple Shortcuts input

### ISSUE THREAD

**Issue by yene** [amebalabs/TRex#31]
Hi, I am unable to Apple Shortcuts working.
I get the error "Unable to run. The input of the shortcut could not be processed."
Could you please show an example on how to use it.

Thank you for your time.

<img width="631" alt="shot 2024-02-18 at 18 09 33" src="https://github.com/amebalabs/TRex/assets/63942/84676bdb-949b-4c6d-a833-23681e26d133">

**Comment by melonamin** [comment]
Here is an [example Shortcut](https://www.icloud.com/shortcuts/20d23bfed13a460588597d42e6b02b86), it will show captured text in a notification.

**Comment by yene** [comment]
@melonamin the provided example gives the same error.
trex: Version 1.6.0 (104)
macos: 14.3.1 (23D60)

**Comment by melonamin** [comment]
Looks like a regression introduced in 1.7.0, you can go back to 1.6.0 while I'm fixing this

**Comment by melonamin** [comment]
> trex: Version 1.6.0 (104)

Interesting, I can reproduce it on 1.7.0 but not on 1.6.0, looking into it

**Comment by yene** [comment]
If it works on your machine but not mine, it is probably sandbox entitlement. How do you execute the shortcuts?

**Comment by melonamin** [comment]
> How do you execute the shortcuts?

`/usr/bin/shortcuts run <shortcut name> -i <input>`

As a quick test, can you try launching the shortcut from TRex Settings? Press "Play" button:

![Screenshot 2024-03-27 at 10 34 24](https://github.com/amebalabs/TRex/assets/222100/b0feac80-76f5-4db8-b1af-9d95d2b02e5b)
