### ISSUE TITLE
"TRex" can access this computer's screen and audio

### ISSUE THREAD

**Issue by becauseim** [amebalabs/TRex#34]
permission granted, but the error still comes out.
macOS Version 15.0 Beta (24A5279h)

![Screenshot 2024-07-03 at 02 32 40](https://github.com/amebalabs/TRex/assets/23287366/c93fd55a-0b4f-483b-9155-01c9e3b2dd4c)

![Screenshot 2024-07-03 at 03 00 36](https://github.com/amebalabs/TRex/assets/23287366/16df9f4e-409c-4b78-b396-01c5fc91212d)

**Comment by melonamin** [comment]
All apps that access screen recording APIs are doing this on BETA now, I didn't have time to look into it and not planning to until later in the BETA cycle.

**Comment by melonamin** [comment]
Documenting the story https://sixcolors.com/post/2024/08/apples-permissions-features-are-out-of-balance/

**Comment by melonamin** [comment]
The issue became less jarring as of the latest beta; now you have an option "Allow for a Month". Keeping my fingers crossed for a better solution from Apple

https://9to5mac.com/2024/08/14/macos-sequoia-screen-recording-prompt-monthly/

**Comment by melonamin** [comment]
Closing, nothing I can do here
