### ISSUE TITLE
[Enhancement] Option-click on menu bar icon to trigger capture

### ISSUE THREAD

**Issue by Mateus109** [amebalabs/TRex#42]
Per title, option-click on the TRex menu bar icon to trigger capture mode (or another default action, configured within settings).

**Comment by Mateus109** [comment]
Amazing! Thanks

**Comment by Mateus109** [comment]
There seems to be a minor bug with the option key graphic (at least on macOS 14.7.1)
![Image](https://github.com/user-attachments/assets/29c8f89a-4bdc-44d2-8324-b3b5a4455c49)

**Comment by melonamin** [comment]
@Mateus109 thanks, fixed in 1.8.1
