### ISSUE TITLE
TRex doesn't do anything after a screen capture

### ISSUE THREAD

**Issue by beingalink** [amebalabs/TRex#5]
I just got TRex from the app store and enabled screen capture rights for it. When I do a screen capture by clicking TRex in the menubar > "Capture Text", nothing happens, no window pops up or such. Did I misunderstand sth regarding the usage or is there a bug? I'm on macOS 11.3.1, MacBook Pro (13 Zoll, 2019, 4 Thunderbolt 3).

**Comment by melonamin** [comment]
Hm, I just did a clean install from the App Store and it works as expected.
After you click on Capture Text you should see a crosshair, like one you see in macOS screenshot tool. You don't see it?

Can you check if you have anything in Console.app output relevant to TRex?

**Comment by beingalink** [comment]
Sorry, I wasn't precise enough. I get the crosshair and I make a selection of text in an image but afterwards nothing happens.

**Comment by melonamin** [comment]
Ah, that's the point, recognized text is copied to the clipboard.

In settings you can configure additional behavior, for example you can automatically open a link in Safari. 

But by default it just puts the text into system clipboard.

**Comment by beingalink** [comment]
OK, I'm embarrassed. Clearly just PEBCAC. Sorry for bothering you!

**Comment by quark67** [comment]
Perhaps you could add a word about this behaviour (the recognized text is only copied in the clipboard) in the README.md file.

Because when I see https://github.com/amebalabs/TRex/raw/main/Resources/demo.gif I expected a window with the recognized text as in the gif.

Thanks.

**Comment by melonamin** [comment]
@quark67 Yes, I will clarify this in the Readme.  

> I expected a window with the recognized text as in the gif. 

You are not the first one to assume that, In my nerdy head I just assumed that everybody knows this app(Tot)

**Comment by quark67** [comment]
You're right, I don't know this app (Tot).
