### ISSUE TITLE
Unneeded hyphenation

### ISSUE THREAD

**Issue by reagle** [amebalabs/TRex#6]
I selected some text from the [first page](https://www.amazon.com/gp/product/B07VWKZ2QP?storeType=ebooks&asin=B07VWKZ2QP&revisionId=d5a833b7&format=1&depth=1) of a kindle book and TRex yielded text including:

> hot. A creek rushed behind our tents, and we used it to filter wa-
> ter and cool the beer we'd snagged from the nearby ski town's os-
> tentatiously wood-beamed liquor store.

It seems like TRex is hard wrapping lines and adding hyphenation that is not in the original text?

**Comment by melonamin** [comment]
Yes, currently TRex adds an explicit line break (`\n`) between lines of text. I'm planning to add an option to override this behavior.

**Comment by melonamin** [comment]
Released as 1.3

**Comment by reagle** [comment]
Thanks! I upgraded via homebrew to "v1.3". (BTW: I don't think "v" should be in the version number "v1.3".)

1. What does "Append New Line" in the preferences mean? Is that specific to URLs only?
2. I'm thinking the spurious hyphenation I was seeing was on my side. When Amazon shows the page of a book, as in my example, it apparently reflows it dynamically (i.e., wrapping and hyphenating). So maybe the difference I was seeing between what I thought the source was and what TRex was grabbing wasn't TRex, but a change in the browser's window size and Amazon reflowing.

In any case, thanks for the handy tool!

**Comment by melonamin** [comment]
> (BTW: I don't think "v" should be in the version number "v1.3".)

Yep, I should change this, thanks.

> What does "Append New Line" in the preferences mean? Is that specific to URLs only?

Yes, this is only for URL schemes, it appends a new line in the end of captured text. In my workflow I use this together with [Tot](https://tot.rocks) - I would capture a bunch of text and it will be added to Tot, each capture separated by an empty line.
