### ISSUE TITLE
Preferences option doesn't appear to do anything

### ISSUE THREAD

**Issue by carbocation** [amebalabs/TRex#8]
Version: TRex 1.3 (40)

OS X: Big Sur 11.4 (20F71)

Observation: When accessing TRex from the menu bar, there is an entry for "Preferences". Clicking on that entry does not appear to have any effect. 

Expectation: I'd expect a preferences panel to appear. (I tried to access it because after rebooting my computer, I noticed that TRex wasn't in the menubar, and I'm hoping that the menu has an option to start TRex upon login.)

**Comment by alexwhitman** [comment]
Does it not appear at all, or does it just appear without focus? I've noticed that if I use the "Preferences" or "About TRex..." menu options the windows do appear but behind other windows.

**Comment by carbocation** [comment]
I rebooted and tried this again with no other programs open, and I still saw no window or message.

**Comment by melonamin** [comment]
>  I've noticed that if I use the "Preferences" or "About TRex..." menu options the windows do appear but behind other windows.

Yes, this is a known behavior.

@carbocation  can you share a screen recording? How about "About" screen, can you see it?

**Comment by carbocation** [comment]
Confusingly, I am able to see it now after sleeping the machine. I suspect that this is an issue on my end. I'll try to see if I can narrow down the problem and provide a screen recording if it comes back. I think this issue can probably just be closed.
